# Generated by Django 5.2.17 on 2026-09-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mess",
            options={"verbose_name": "Mess", "verbose_name_plural": "Messes"},
        ),
    ]
