# Generated by Django 5.2.17 on 2026-09-18 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("messes", "0002_alter_mess_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. September 2026", max_length=50),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("LOCKED", "Locked"),
                            ("SETTLED", "Settled"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="month_cycles",
                        to="messes.mess",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ACTIVE")),
                        fields=("mess",),
                        name="unique_active_month_cycle_per_mess",
                    )
                ],
            },
        ),
    ]
