# Generated by Django 5.2.17 on 2026-09-21 12:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0001_initial"),
        ("messes", "0002_alter_mess_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "breakfast",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0.0"), max_digits=3
                    ),
                ),
                (
                    "lunch",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0.0"), max_digits=3
                    ),
                ),
                (
                    "dinner",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0.0"), max_digits=3
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="meals.monthcycle",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_logs",
                        to="messes.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "membership__user__full_name"],
                "unique_together": {("cycle", "membership", "date")},
            },
        ),
    ]
